model:
  soap:
    num_pseudo_species: 4
    cutoff: 5.0
    basis_cutoff_power_spectrum: 400  # controls how large the radial-angular basis is
    radial_basis_type: 'physical'  # 'physical' or 'le'
    basis_scale: 3.0  # controls the initial scale of the physical basis (in Angstroms, does not affect the le basis)
    trainable_basis: true  # whether the radial basis is trainable (i.e. contains a small NN)
    normalize: true  # whether to use normalizations, such as LayerNorm
    contract_center_species: true  # whether to use the Alchamical Compression on the center species
                                   # If false, the center species chemical space will remain unchaged,
                                   # and for each original atom type there will be a separate BPNN
  bpnn:
    hidden_sizes: [32, 32] # hidden sizes of the BPNN layers
    output_size: 1  # output size of the BPNN

training:
  batch_size: 8
  num_epochs: 100
  learning_rate: 0.001
  log_interval: 10
  checkpoint_interval: 25
  per_atom_targets: []  # this specifies whether the model should be trained on a per-atom loss.
                        # In that case, the logger will also output per-atom metrics for that
                        # target. In any case, the final summary will be per-structure.
