# default hyperparameters for the PET-JAX model
model:
  cutoff: 5.0
  d_pet: 128
  num_heads: 2
  num_attention_layers: 3
  mlp_dropout_rate: 0.0
  attention_dropout_rate: 0.0

training:
  batch_size: 16
  num_warmup_steps: 1000
  num_epochs: 10000
  learning_rate: 3e-4
  log_interval: 10
