base_precision: 64

model:
  nu_max: 4
  cutoff_radius: 6.0
  n_element_channels: 16
  radial_basis:
    mlp: true
    type: physical
    E_max: 70.0

training:
  batch_size: 8
  num_epochs: 1000
  learning_rate: 0.001
  early_stopping_patience: 100
  scheduler_patience: 50
  scheduler_factor: 0.5
  log_interval: 10
  checkpoint_interval: 25
  fixed_composition_weights: {}
  per_atom_targets: []
